### ISSUE TITLE
`submove zpr` is broken

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#1210]

**Comment by cbrxyz** [comment]
Example:
```
$ submove zpr 0,0,0
Starting mission  Move
Feedback:
-  Waiting for odom...
-  Odom found!
-  Zeroing roll and pitch
Goal finished with state  ABORTED
Goal unsuccessful
Result: 'Exception occurred in Move mission: AttributeError: 'function' object has no attribute 'zero_roll_and_pitch''
traceback: Traceback (most recent call last):
  File "/home/parallels/catkin_ws/src/mil/mil_common/mil_missions/nodes/mission_server", line 222, in run_with_callback
    return await self.mission.run(parameters)
  File "/home/parallels/catkin_ws/src/mil/SubjuGator/command/subjugator_missions/subjugator_missions/move.py", line 209, in run
    res = await self.move.zero_roll_and_pitch().go(**action_kwargs)
AttributeError: 'function' object has no attribute 'zero_roll_and_pitch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/parallels/catkin_ws/src/mil/mil_common/mil_missions/nodes/mission_server", line 251, in mission_finished_cb
    task_result = task.result()
  File "/home/parallels/catkin_ws/src/mil/mil_common/mil_missions/nodes/mission_server", line 224, in run_with_callback
    raise SubmissionException(self.mission, e) from e
mil_missions_core.exceptions.SubmissionException: Exception occurred in Move mission: AttributeError: 'function' object has no attribute 'zero_roll_and_pitch'
```

Probably something to do with how the Move API was updated last year in #1002.
